# Case studies

* model: RF

In [1]:
import pandas as pd
import os

from IPython.display import Image, display

from dataset.splitting_dataset import split_dataframe
from training.constants import CHOSEN_MODEL, MODELS_RESULTS_DIR, PATH_TO_DATASET, SET_NAME

os.chdir("..")

In [2]:
TEST_RESULTS_FILE = os.path.join(MODELS_RESULTS_DIR, f"{SET_NAME}_{CHOSEN_MODEL}_test.csv")
TRAIN_RESULTS_FILE = os.path.join(MODELS_RESULTS_DIR, f"{SET_NAME}_{CHOSEN_MODEL}_train.csv")

bestiaries = pd.read_csv(PATH_TO_DATASET, index_col=0)
X_train, X_test, y_train, y_test = split_dataframe(bestiaries, drop_book_column=False, drop_name_column=False)

y_test += 1
y_train += 1

y_test_pred = pd.read_csv(TEST_RESULTS_FILE, header=None)[0].to_numpy()
y_train_pred = pd.read_csv(TRAIN_RESULTS_FILE, header=None)[0].to_numpy()

## Monsters with high error - train

In [3]:
X_train["level"] = y_train
X_train["pred_level"] =  y_train_pred
X_train["level_diff"] = y_train - y_train_pred
X_train[X_train["level_diff"] > 2][["name", "book", "level", "pred_level", "level_diff"]]

,name,book,level,pred_level,level_diff
5413,Kaleb Valdemar's Body,Pathfinder #200: Seven Dooms for Sandpoint,13,10.772,2.228

### Dancing Night Parade

Link: [nethys](https://2e.aonprd.com/Monsters.aspx?ID=1519)

Source Pathfinder #168: King of the Mountain pg. 41

Level: 19

It has the Troop trait, meaning it represents a mass of spirits acting together, not a single creature. Mechanically, it behaves more like a moving crowd, swarm, or environmental event than a normal monster.

Its main gimmick is a festival/parade aura (“Riotous Parade”) that forces nearby creatures to laugh, dance, lose reactions, and struggle to concentrate.

It doesn’t even have a normal Strike routine like most monsters. Instead, it uses area effects and troop mechanics.

This thing is closer to:

* a supernatural street festival,
* a haunted procession,
* a living magical phenomenon

In [4]:
X_train[X_train["name"] == "Dancing Night Parade"]

,str,dex,con,int,wis,cha,ac,hp,perception,fortitude,...,ranged_max_bonus,avg_ranged_dmg,max_spell_lvl,spell_dc,spell_attack,book,name,level,pred_level,level_diff
1029,8,7,5,5,5,6,40,450,28,32,...,0,0.0,0,0,0,Pathfinder #168: King of the Mountain,Dancing Night Parade,20,19.256,0.744

### Phantasmal Protagonist

Link: [nethys](https://2e.aonprd.com/Spells.aspx?ID=1230)

Source: Pathfinder Kingmaker

It is accually a 4th-rank spell with H, AC and speed filled

You create a phantasmal incarnation of a significant character from a novel, historical work, or religious parable. The phantasm is Medium, regardless of the size of the character as it was described in the inspirational work. When you Cast the Spell, decide what theme the protagonist is, choosing from hero, ally, or villain. The protagonist appears in an unoccupied space within range, and the first time each round that you Sustain the Spell, you can direct the protagonist to Stride or take the action granted by its theme. The phantasmal protagonist has a speed of 25 feet and an AC of 22. Its saving throw modifiers, Perception modifier, and skill modifiers are +12. It has 90 HP.
Ally The protagonist takes the form of a recognizable support character. Its thematic action is to grant an adjacent creature 4d4 temporary Hit Points, which last for 1 round.
Hero The protagonist takes the form of a legendary hero. Its thematic action is to attempt a melee Strike, using your spell attack roll to make the attack and inflicting 4d6+6 mental damage on a hit.
Villain The protagonist takes the form of a notorious villain. Its thematic action is to harry and mock an adjacent target. The target must succeed at a Will save or become flat-footed (slowed 1 on a critical failure) until the end of your next turn.

In [5]:
X_train[X_train["name"] == "Phantasmal Protagonist"]

,str,dex,con,int,wis,cha,ac,hp,perception,fortitude,...,ranged_max_bonus,avg_ranged_dmg,max_spell_lvl,spell_dc,spell_attack,book,name,level,pred_level,level_diff
1313,0,0,0,0,0,0,10,90,0,0,...,0,0.0,0,0,0,Pathfinder Kingmaker,Phantasmal Protagonist,5,4.281257,0.718743

### Kaleb Valdemar's Body

Link: [nethys](https://2e.aonprd.com/Monsters.aspx?ID=3358)

In [6]:
X_train[X_train["name"] == "Kaleb Valdemar's Body"]

,str,dex,con,int,wis,cha,ac,hp,perception,fortitude,...,ranged_max_bonus,avg_ranged_dmg,max_spell_lvl,spell_dc,spell_attack,book,name,level,pred_level,level_diff
5413,4,1,2,7,5,6,20,112,9,15,...,0,0.0,6,29,21,Pathfinder #200: Seven Dooms for Sandpoint,Kaleb Valdemar's Body,13,10.772,2.228

### Tardigrade Swarm

Link: [nethys](https://2e.aonprd.com/Monsters.aspx?ID=3317)

Sourse: Pathfinder Howl of the Wild	

Special type of attack with kinf of auta affect:

 Each enemy in the swarm's space takes 4d8 piercing damage (DC 32 basic Reflex save). Creatures that fail their save become drained 1 or increase their drained condition by one, to a maximum of drained 4

In [7]:
X_train[X_train["name"] == "Tardigrade Swarm"]

,str,dex,con,int,wis,cha,ac,hp,perception,fortitude,...,ranged_max_bonus,avg_ranged_dmg,max_spell_lvl,spell_dc,spell_attack,book,name,level,pred_level,level_diff
1179,2,4,6,-5,3,1,28,140,21,26,...,0,0.0,0,0,0,Pathfinder Howl of the Wild,Tardigrade Swarm,13,12.452,0.548

### Imp Minion (3-4)

Source: Pathfinder Society Scenario #7-01

Not fully independent monster

A lot of empty stats

In [8]:
X_train[X_train["name"] == "Imp Minion (3-4)"]

,str,dex,con,int,wis,cha,ac,hp,perception,fortitude,...,ranged_max_bonus,avg_ranged_dmg,max_spell_lvl,spell_dc,spell_attack,book,name,level,pred_level,level_diff
4996,0,0,0,0,0,0,0,1,0,0,...,0,0.0,0,0,0,Pathfinder Society Scenario #7-01: Intro to th...,Imp Minion (3-4),3,2.6123,0.3877

## Monsters with high error - test

In [9]:
X_test["level"] = y_test
X_test["pred_level"] =  y_test_pred
X_test["level_diff"] = y_test - y_test_pred
X_test[X_test["level_diff"] > 1.5][["name", "book", "level", "pred_level", "level_diff"]]

,name,book,level,pred_level,level_diff
2510,Reflection,Pathfinder Dark Archive (Remastered),7,5.160000,1.840000
5032,The Scourge of Woodsedge,Pathfinder Society Scenario #7-10: Shattered B...,16,14.126000,1.874000
1114,Snowy Owl,Pathfinder Adventure Path: Gatewalkers,8,5.560000,2.440000
1069,Symbiotic Amoeba,Pathfinder Adventure Path: Gatewalkers,5,3.203000,1.797000
4940,The Husk of Deskari,Pathfinder Society Scenario #6-19: What Walks ...,15,13.298000,1.702000
4939,The Husk of Deskari (13-14),Pathfinder Society Scenario #6-19: What Walks ...,18,16.340333,1.659667
4923,Screaming Grub Undead,Pathfinder Society Scenario #6-16: The Heart o...,8,5.304000,2.696000
674,Raised Cavalry,Pathfinder Claws of the Tyrant,20,18.417333,1.582667
4894,Young Giant Viper,Pathfinder Society Scenario #6-13: All That Gl...,3,1.110000,1.890000
4884,Inhabited Statue,Pathfinder Society Scenario #6-13: All That Gl...,4,1.938000,2.062000

### Snowy Owl

[link](https://2e.aonprd.com/NPCs.aspx?ID=4255)

In [10]:
X_test[X_test.name == "Snowy Owl"]

,str,dex,con,int,wis,cha,ac,hp,perception,fortitude,...,ranged_max_bonus,avg_ranged_dmg,max_spell_lvl,spell_dc,spell_attack,book,name,level,pred_level,level_diff
1114,0,1,2,1,5,4,21,60,16,11,...,0,0.0,4,18,12,Pathfinder Adventure Path: Gatewalkers,Snowy Owl,8,5.56,2.44

### Symbiotic Amoeba

Not a real monster

*"Symbiotic Amoeba An amoeba produced by the amelekana is a Tiny, mindless, semi-independent creature controlled by the amelekana. It has the minion trait, AC 15, 1 Hit Point, and the same skills and saving throws as the amelekana. Each round, the amelekana can Command a Minion to make an amoeba Step or Swim 20 feet and make a pseudopod Strike (Melee pseudopod +13, Damage 2d4 acid). If an amelekana is killed, its symbiotic amoebas are also killed by the host creature's psychic backlash. An amelekana can have up to three extant symbiotic amoebas at a time."*

[link](https://2e.aonprd.com/Monsters.aspx?ID=4214)

In [11]:
X_test[X_test.name == "Symbiotic Amoeba"]

,str,dex,con,int,wis,cha,ac,hp,perception,fortitude,...,ranged_max_bonus,avg_ranged_dmg,max_spell_lvl,spell_dc,spell_attack,book,name,level,pred_level,level_diff
1069,0,0,0,0,0,0,15,1,0,14,...,0,0.0,0,0,0,Pathfinder Adventure Path: Gatewalkers,Symbiotic Amoeba,5,3.203,1.797

In [12]:
url = "https://2e.aonprd.com/Images/Monsters/Amelekana.png"
display(Image(url=url, width=500))

In [13]:
X_test[X_test.name == "Amelekana"]

,str,dex,con,int,wis,cha,ac,hp,perception,fortitude,...,ranged_max_bonus,avg_ranged_dmg,max_spell_lvl,spell_dc,spell_attack,book,name,level,pred_level,level_diff
1053,5,1,4,-3,4,0,21,72,14,14,...,14,13.0,0,0,0,Pathfinder Adventure Path: Gatewalkers,Amelekana,5,5.446,-0.446

### Screaming Grub Undead

In [14]:
X_test[X_test.name == "Screaming Grub Undead"]

,str,dex,con,int,wis,cha,ac,hp,perception,fortitude,...,ranged_max_bonus,avg_ranged_dmg,max_spell_lvl,spell_dc,spell_attack,book,name,level,pred_level,level_diff
4923,0,0,0,0,0,0,23,1,0,12,...,0,0.0,0,0,0,Pathfinder Society Scenario #6-16: The Heart o...,Screaming Grub Undead,8,5.304,2.696

### Inhabited Statue

In [15]:
X_test[X_test.name == "Inhabited Statue"]

,str,dex,con,int,wis,cha,ac,hp,perception,fortitude,...,ranged_max_bonus,avg_ranged_dmg,max_spell_lvl,spell_dc,spell_attack,book,name,level,pred_level,level_diff
4884,0,0,0,0,0,0,19,15,0,10,...,0,0.0,0,0,0,Pathfinder Society Scenario #6-13: All That Gl...,Inhabited Statue,4,1.938,2.062

### Summary

Most creatures are not true monsters but some variations, semi-independent creatures created out of a different creature.

* Snowy Owl	- by default no flying speed but can use Ruun's Wings [one-action] to fly 25 feet (not included inside stats)
* Symbiotic Amoeba	- semi-independent monster with level and skills copied from Amelekana, some stats not copied but set to `0` without adjusting level
* Screaming Grub Undead	- one of Society creatures, seems like some stats might be missing looking at a lot of `0` but high level (`8`), monster with `1 HP`
* Inhabited Statue - one of Society creatures, seems like some stats might be missing looking at a lot of `0`, level lower then for *Screaming Grub Undead*, more `HP` so level difference is not that large

### Reflection


* Source Dark Archives (Remastered) pg. 180
* Ancestry Page [Reflection](https://2e.aonprd.com/Ancestries.aspx?ID=97)
* You were created as a duplicate of another creature, intentionally or accidentally, though you might not know of your origins. Other than a minor mark or two, you look just like your progenitor. You gain the reflection trait, in addition to the traits from your ancestry. You don't need to attempt Deception checks to Impersonate your progenitor unless you're interacting with people who know them personally or you do something known to be out of character for them. The GM might require you to roll a Deception check in other circumstances, such as if you're mirror-risen and interacting with someone who has seen an accurate likeness of your progenitor and might notice a distinguishing feature on the reverse side. You can choose from reflection feats and feats from your ancestry whenever you gain an ancestry feat.*

In [16]:
X_test[X_test.name == "Reflection"]

,str,dex,con,int,wis,cha,ac,hp,perception,fortitude,...,ranged_max_bonus,avg_ranged_dmg,max_spell_lvl,spell_dc,spell_attack,book,name,level,pred_level,level_diff
2510,0,0,0,0,0,0,24,30,0,11,...,0,0.0,0,0,0,Pathfinder Dark Archive (Remastered),Reflection,7,5.16,1.84

## Chosen monsters

### Trolls

In [17]:
X_test[X_test.name.str.contains("Troll")]

,str,dex,con,int,wis,cha,ac,hp,perception,fortitude,...,ranged_max_bonus,avg_ranged_dmg,max_spell_lvl,spell_dc,spell_attack,book,name,level,pred_level,level_diff
2910,6,1,6,-2,4,3,24,190,16,19,...,0,0.0,0,0,0,Pathfinder Monster Core 2,Two-Headed Troll,9,8.640000,0.360000
2908,4,1,5,-3,1,-2,17,65,6,14,...,0,0.0,0,0,0,Pathfinder Monster Core 2,Trollhound,4,4.317967,-0.317967
2696,5,2,5,-2,2,-2,19,90,10,13,...,0,0.0,0,0,0,Pathfinder Monster Core 2,Ice Troll,5,5.136000,-0.136000
2708,8,4,8,-1,6,4,35,360,26,31,...,0,0.0,0,0,0,Pathfinder Monster Core 2,Jotund Troll,16,15.738000,0.262000
2569,6,2,6,-2,2,-2,22,135,14,16,...,16,14.5,0,0,0,Pathfinder Monster Core 2,Cavern Troll,7,6.898000,0.102000

### Dragons: Wish, Coral, Executor, Umbral, Whisper, Omen, Mocking

In [19]:
X_test[X_test.name.str.contains(r"Omen |Wish |Coral |Cloud |Whisper |Executor |Umbral |Mocking ")].sort_values(by="name")

,str,dex,con,int,wis,cha,ac,hp,perception,fortitude,...,ranged_max_bonus,avg_ranged_dmg,max_spell_lvl,spell_dc,spell_attack,book,name,level,pred_level,level_diff
1417,11,6,8,6,8,8,48,475,39,39,...,0,0.0,9,45,37,Pathfinder Lost Omens Draconic Codex,Cloud Archdragon,22,21.974000,0.026000
1416,11,6,8,6,8,8,48,475,39,39,...,0,0.0,10,45,37,Pathfinder Lost Omens Draconic Codex,Cloud Archdragon (Spellcaster),22,21.976000,0.024000
1419,8,3,5,4,5,5,36,255,28,25,...,0,0.0,4,34,26,Pathfinder Lost Omens Draconic Codex,Cloud Dragon (Adult),15,15.232000,-0.232000
1418,8,3,5,4,5,5,36,255,28,25,...,0,0.0,6,34,26,Pathfinder Lost Omens Draconic Codex,"Cloud Dragon (Adult, Spellcaster)",15,15.224000,-0.224000
1421,10,4,7,5,6,6,43,355,34,34,...,0,0.0,5,41,33,Pathfinder Lost Omens Draconic Codex,Cloud Dragon (Ancient),20,20.036000,-0.036000
1420,10,4,7,5,6,6,43,355,34,34,...,0,0.0,9,41,33,Pathfinder Lost Omens Draconic Codex,"Cloud Dragon (Ancient, Spellcaster)",20,20.070000,-0.070000
1423,7,2,5,2,3,3,30,175,22,19,...,0,0.0,1,29,21,Pathfinder Lost Omens Draconic Codex,Cloud Dragon (Young),11,11.098000,-0.098000
1422,7,2,5,2,3,3,30,175,22,19,...,0,0.0,4,29,21,Pathfinder Lost Omens Draconic Codex,"Cloud Dragon (Young, Spellcaster)",11,11.088000,-0.088000
1427,10,6,7,6,6,7,45,400,38,38,...,0,0.0,0,0,0,Pathfinder Lost Omens Draconic Codex,Coral Archdragon,22,21.512000,0.488000
1426,10,6,7,6,6,7,45,400,38,38,...,0,0.0,10,44,36,Pathfinder Lost Omens Draconic Codex,Coral Archdragon (Spellcaster),22,21.538000,0.462000
2584,7,2,5,3,5,7,32,215,22,25,...,0,0.0,0,0,0,Pathfinder Monster Core 2,Coral Dragon (Adult),13,13.002000,-0.002000
2583,7,2,5,3,5,7,32,215,22,25,...,0,0.0,6,32,24,Pathfinder Monster Core 2,"Coral Dragon (Adult, Spellcaster)",13,13.018000,-0.018000
2586,9,5,6,5,5,6,39,315,32,32,...,0,0.0,0,0,0,Pathfinder Monster Core 2,Coral Dragon (Ancient),18,17.842000,0.158000
2585,9,5,6,5,5,6,39,315,32,32,...,0,0.0,8,38,30,Pathfinder Monster Core 2,"Coral Dragon (Ancient, Spellcaster)",18,17.750000,0.250000
2588,6,2,4,2,2,6,26,135,16,18,...,0,0.0,0,0,0,Pathfinder Monster Core 2,Coral Dragon (Young),9,8.990000,0.010000
2587,6,2,4,2,2,6,26,135,16,18,...,0,0.0,4,26,18,Pathfinder Monster Core 2,"Coral Dragon (Young, Spellcaster)",9,8.972000,0.028000
1454,11,5,6,4,7,5,45,400,35,35,...,0,0.0,9,44,0,Pathfinder Lost Omens Draconic Codex,Executor Archdragon,22,21.052000,0.948000
1453,11,5,6,4,7,5,45,400,35,35,...,0,0.0,9,44,0,Pathfinder Lost Omens Draconic Codex,Executor Archdragon (Spellcaster),22,21.052000,0.948000
1456,8,3,4,2,5,3,33,235,23,25,...,0,0.0,5,33,0,Pathfinder Lost Omens Draconic Codex,Executor Dragon (Adult),14,14.120000,-0.120000
1455,8,3,4,2,5,3,33,235,23,25,...,0,0.0,6,33,0,Pathfinder Lost Omens Draconic Codex,"Executor Dragon (Adult, Spellcaster)",14,14.126000,-0.126000
1458,9,4,5,3,6,4,42,335,30,32,...,0,0.0,9,40,0,Pathfinder Lost Omens Draconic Codex,Executor Dragon (Ancient),19,19.097000,-0.097000
1457,9,4,5,3,6,4,42,335,30,32,...,0,0.0,9,40,0,Pathfinder Lost Omens Draconic Codex,"Executor Dragon (Ancient, Spellcaster)",19,19.097000,-0.097000
1460,6,2,3,1,4,2,27,155,18,18,...,0,0.0,5,28,0,Pathfinder Lost Omens Draconic Codex,Executor Dragon (Young),10,9.892000,0.108000
1459,6,2,3,1,4,2,27,155,18,18,...,0,0.0,5,28,0,Pathfinder Lost Omens Draconic Codex,"Executor Dragon (Young, Spellcaster)",10,9.892000,0.108000
1484,9,7,6,7,6,10,45,420,39,33,...,36,28.0,2,42,0,Pathfinder Lost Omens Draconic Codex,Mocking Archdragon,21,21.260000,-0.260000
1483,9,7,6,7,6,10,45,420,39,33,...,36,28.0,10,42,0,Pathfinder Lost Omens Draconic Codex,Mocking Archdragon (Spellcaster),21,21.282000,-0.282000
1486,6,4,3,4,3,7,32,215,25,20,...,24,17.5,2,32,0,Pathfinder Lost Omens Draconic Codex,Mocking Dragon (Adult),13,13.154000,-0.154000
1485,6,4,3,4,3,7,32,215,25,20,...,24,17.5,6,32,0,Pathfinder Lost Omens Draconic Codex,"Mocking Dragon (Adult, Spellcaster)",13,13.174000,-0.174000
1488,7,5,4,5,4,9,39,325,32,27,...,31,23.5,2,38,0,Pathfinder Lost Omens Draconic Codex,Mocking Dragon (Ancient),18,17.595667,0.404333
1487,7,5,4,5,4,9,39,325,32,27,...,31,23.5,8,38,0,Pathfinder Lost Omens Draconic Codex,"Mocking Dragon (Ancient, Spellcaster)",18,17.620667,0.379333
1490,5,3,2,3,2,6,26,135,19,14,...,17,13.0,2,26,0,Pathfinder Lost Omens Draconic Codex,Mocking Dragon (Young),9,9.110000,-0.110000
1489,5,3,2,3,2,6,26,135,19,14,...,17,13.0,4,26,0,Pathfinder Lost Omens Draconic Codex,"Mocking Dragon (Young, Spellcaster)",9,9.112000,-0.112000
1500,9,7,8,10,8,6,44,360,35,32,...,0,0.0,10,44,36,Pathfinder Lost Omens Draconic Codex,Omen Archdragon,21,20.724000,0.276000
1499,9,7,8,10,8,6,44,360,35,32,...,0,0.0,10,44,36,Pathfinder Lost Omens Draconic Codex,Omen Archdragon (Spellcaster),21,20.724000,0.276000
1566,12,7,10,7,10,6,48,525,40,42,...,0,0.0,5,43,0,Pathfinder Lost Omens Draconic Codex,Umbral Archdragon,22,21.974000,0.026000
1565,12,7,10,7,10,6,48,525,40,42,...,0,0.0,10,43,0,Pathfinder Lost Omens Draconic Codex,Umbral Archdragon (Spellcaster),22,21.954000,0.046000
1568,8,5,6,4,6,4,36,275,26,27,...,0,0.0,5,33,0,Pathfinder Lost Omens Draconic Codex,Umbral Dragon (Adult),16,15.480000,0.520000
1567,8,5,6,4,6,4,36,275,26,27,...,0,0.0,7,33,0,Pathfinder Lost Omens Draconic Codex,"Umbral Dragon (Adult, Spellcaster)",16,15.498000,0.502000
1570,10,6,7,5,7,5,44,375,33,34,...,0,0.0,5,39,0,Pathfinder Lost Omens Draconic Codex,Umbral Dragon (Ancient),21,20.648000,0.352000
1569,10,6,7,5,7,5,44,375,33,34,...,0,0.0,9,39,0,Pathfinder Lost Omens Draconic Codex,"Umbral Dragon (Ancient, Spellcaster)",21,20.644000,0.356000
1572,6,4,5,3,5,3,30,195,22,22,...,0,0.0,2,27,0,Pathfinder Lost Omens Draconic Codex,Umbral Dragon (Young),12,11.862000,0.138000
1571,6,4,5,3,5,3,30,195,22,22,...,0,0.0,5,27,0,Pathfinder Lost Omens Draconic Codex,"Umbral Dragon (Young, Spellcaster)",12,11.842000,0.158000
1606,8,6,7,10,7,9,44,370,33,35,...,0,0.0,9,42,34,Pathfinder Lost Omens Draconic Codex,Whisper Archdragon,21,20.594000,0.406000
1605,8,6,7,10,7,9,44,370,33,35,...,0,0.0,9,42,34,Pathfinder Lost Omens Draconic Codex,Whisper Archdragon (Spellcaster),21,20.630000,0.370000
2942,5,3,4,7,4,6,31,190,21,21,...,0,0.0,5,30,0,Pathfinder Monster Core 2,Whisper Dragon (Adult),12,11.988000,0.012000
2941,5,3,4,7,4,6,31,190,21,21,...,0,0.0,5,30,0,Pathfinder Monster Core 2,"Whisper Dragon (Adult, Spellcaster)",12,11.988000,0.012000
2944,7,5,6,9,6,8,39,290,28,28,...,0,0.0,8,37,0,Pathfinder Monster Core 2,Whisper Dragon (Ancient),17,17.046000,-0.046000
2943,7,5,6,9,6,8,39,290,28,28,...,0,0.0,8,37,0,Pathfinder Monster Core 2,"Whisper Dragon (Ancient, Spellcaster)",17,17.046000,-0.046000
2946,4,2,3,3,2,3,25,110,15,15,...,0,0.0,4,25,0,Pathfinder Monster Core 2,Whisper Dragon (Young),8,8.048000,-0.048000
2945,4,2,3,3,2,3,25,110,15,15,...,0,0.0,4,25,0,Pathfinder Monster Core 2,"Whisper Dragon (Young, Spellcaster)",8,8.048000,-0.048000
1608,8,6,6,11,6,10,48,475,38,35,...,0,0.0,7,45,0,Pathfinder Lost Omens Draconic Codex,Wish Archdragon,22,21.834000,0.166000
1607,8,6,6,11,6,10,48,475,38,35,...,0,0.0,10,45,0,Pathfinder Lost Omens Draconic Codex,Wish Archdragon (Spellcaster),22,21.848000,0.152000
1610,5,4,4,7,4,6,35,260,26,24,...,0,0.0,5,34,0,Pathfinder Lost Omens Draconic Codex,Wish Dragon (Adult),15,14.942000,0.058000
1609,5,4,4,7,4,6,35,260,26,24,...,0,0.0,6,34,0,Pathfinder Lost Omens Draconic Codex,"Wish Dragon (Adult, Spellcaster)",15,14.948000,0.052000
1612,6,5,5,9,5,8,42,360,32,31,...,0,0.0,5,41,0,Pathfinder Lost Omens Draconic Codex,Wish Dragon (Ancient),20,19.608000,0.392000
1611,6,5,5,9,5,8,42,360,32,31,...,0,0.0,8,41,0,Pathfinder Lost Omens Draconic Codex,"Wish Dragon (Ancient, Spellcaster)",20,19.610000,0.390000
1614,5,4,4,6,4,5,29,180,18,18,...,0,0.0,4,29,0,Pathfinder Lost Omens Draconic Codex,Wish Dragon (Young),11,10.894000,0.106000
1613,5,4,4,6,4,5,29,180,18,18,...,0,0.0,4,29,0,Pathfinder Lost Omens Draconic Codex,"Wish Dragon (Young, Spellcaster)",11,10.894000,0.106000